// Catalogo dei giochi: lo usano la home e la Sala 3D.
// Descrizioni volutamente brevi, una riga sola.
export const GAMES = [
  {
    id: 'gts',
    href: '/gts',
    icon: 'note',
    title: 'Guess the Song',
    description: 'Indovina la canzone prima degli altri.',
    tags: ['Online'],
    accent: '#ff4fd8',
  },
  {
    id: 'anno',
    href: '/anno',
    icon: 'hourglass',
    title: "Indovina l'Anno",
    description: "Chi va più vicino all'anno vince.",
    tags: ['Online'],
    accent: '#ffd23f',
  },
  {
    id: 'giorno',
    href: '/anno/giorno',
    icon: 'calendar',
    title: "L'Anno del Giorno",
    description: '10 carte al giorno, una classifica.',
    tags: ['Da solo', 'Ogni giorno'],
    accent: '#39ff88',
  },
  {
    id: 'impostore',
    href: '/impostore',
    icon: 'spy',
    title: 'Impostore',
    description: 'Uno di voi bluffa. Scopritelo.',
    tags: ['1 telefono'],
    accent: '#3ee8ff',
  },
  {
    id: 'bomba',
    href: '/bomba',
    icon: 'bomb',
    title: 'Passa la Bomba',
    description: 'Dì una parola e passa. Non farla scoppiare.',
    tags: ['1 telefono'],
    accent: '#ff8c1a',
    isNew: true,
  },
];
